//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_KhoaHocOnl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASSIGNMENT
    {
        public string ASSIGNMENTID { get; set; }
        public string ID_COURSE { get; set; }
        public string TITLE_ASSIGNMENT { get; set; }
        public string Description_ASSIGNMENT { get; set; }
        public Nullable<System.DateTime> DueDate_ASSIGNMENT { get; set; }
        public string Type_ASSIGNMENT { get; set; }
        public Nullable<double> POINTS { get; set; }
    
        public virtual COURSE COURSE { get; set; }
    }
}
