//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_KhoaHocOnl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COURSE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public COURSE()
        {
            this.ASSIGNMENTS = new HashSet<ASSIGNMENTS>();
            this.GRADES = new HashSet<GRADES>();
            this.QUIZZES = new HashSet<QUIZZES>();
            this.ORDER_COURSE = new HashSet<ORDER_COURSE>();
        }
    
        public string MA_COURSE { get; set; }
        public string MA_TYPECOURSE { get; set; }
        public string MA_GIANGVIEN { get; set; }
        public string NAME_COURSE { get; set; }
        public string DESCRIPTION_COURSE { get; set; }
        public double PRICE_COURSE { get; set; }
        public string STATUS_COURSE { get; set; }
        public string THUMBNAIL { get; set; }
        public int COUNT_LESSON_COURSE { get; set; }
        public string LEVEL_COURSE { get; set; }
        public System.DateTime CREATED_AT_COURSE { get; set; }
        public System.DateTime UPDATE_AT_COURSE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ASSIGNMENTS> ASSIGNMENTS { get; set; }
        public virtual GIANGVIEN GIANGVIEN { get; set; }
        public virtual TYPE_COURSE TYPE_COURSE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GRADES> GRADES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QUIZZES> QUIZZES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDER_COURSE> ORDER_COURSE { get; set; }
    }
}
