//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_KhoaHocOnl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FEEDBACK
    {
        public string FEEDBACKID { get; set; }
        public string ID_USER { get; set; }
        public string ID_COURSE { get; set; }
        public System.DateTime DATE_FEEDBACK { get; set; }
        public string TITLE_FEEDBACK { get; set; }
        public string TEXT_FEEDBACK { get; set; }
        public Nullable<int> RATE_FEEDBACK { get; set; }
    
        public virtual USER_COURSE USER_COURSE { get; set; }
    }
}
