//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_KhoaHocOnl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GIANGVIEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GIANGVIEN()
        {
            this.COURSE = new HashSet<COURSE>();
        }
    
        public string MA_GIANGVIEN { get; set; }
        public string MA_COURSE { get; set; }
        public string TEN_GIAOVIEN { get; set; }
        public string STATUS_COURSE { get; set; }
        public string THUMBNAIL { get; set; }
        public System.DateTime D_CREATED { get; set; }
        public string LEVEL_GV { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COURSE> COURSE { get; set; }
    }
}
